import PDFDocument from "pdfkit";
import type { ReportData } from "../ai/report-insights";

// ---------------------------------------------------------------------------
// Types (unchanged public interface)
// ---------------------------------------------------------------------------
interface PdfReportInput {
  title: string;
  month: string;
  reportData: ReportData;
  aiInsights: string | null;
  recurringBills: Array<{
    description: string;
    friendly_name: string | null;
    amount: number;
    recurrence_interval: string | null;
    next_due_date: string | null;
  }>;
  incomeSources: Array<{
    source_name: string;
    amount: number;
    frequency: string;
    attributed_to_name: string | null;
  }>;
  memberContributions?: Array<{
    display_name: string;
    income: number;
    expenses: number;
  }>;
  subscriptionsPaid: Array<{
    name: string;
    amount: number;
    category: string | null;
    recurrence_interval: string;
  }>;
  goalProgress: Array<{
    name: string;
    goal_type: string;
    current: number;
    target: number;
    category_name: string | null;
    target_date: string | null;
  }>;
  savingsRecommendations: Array<{
    category: string;
    amount: number;
    percentage: number;
    suggestion: string;
  }>;
}

// ---------------------------------------------------------------------------
// Color palette
// ---------------------------------------------------------------------------
const C = {
  headerBg: "#0f766e",
  headerLight: "#14b8a6",
  income: "#10b981",
  incomeBg: "#ecfdf5",
  expense: "#ef4444",
  expenseBg: "#fef2f2",
  net: "#3b82f6",
  netBg: "#eff6ff",
  savings: "#8b5cf6",
  savingsBg: "#f5f3ff",
  amber: "#f59e0b",
  amberBg: "#fffbeb",
  dark: "#1e293b",
  muted: "#64748b",
  divider: "#e2e8f0",
  rowAlt: "#f8fafc",
  white: "#ffffff",
};

const BAR_COLORS = [
  "#10b981", "#3b82f6", "#8b5cf6", "#f59e0b",
  "#ef4444", "#06b6d4", "#ec4899", "#64748b",
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function fmt(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}

// Active footer context — set per buildReportPdf call for safe page breaks
let activeFooterCtx: {
  doc: PDFKit.PDFDocument;
  generatedDate: string;
  pageCounter: { value: number };
} | null = null;

/** Draw footer on current page and start a new one. */
function newPage(doc: PDFKit.PDFDocument) {
  if (activeFooterCtx) {
    drawPageFooter(
      doc,
      activeFooterCtx.generatedDate,
      activeFooterCtx.pageCounter
    );
  }
  doc.addPage();
}

function ensureSpace(doc: PDFKit.PDFDocument, needed: number) {
  if (doc.y > doc.page.height - doc.page.margins.bottom - needed) {
    newPage(doc);
  }
}

/** Estimate minimum height to start a section (title + first few rows). */
function sectionStartHeight(rowCount: number, rowHeight = 18): number {
  const visibleRows = Math.min(rowCount, 3);
  return 30 + (visibleRows + 1) * rowHeight + 10;
}

function roundedRect(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
  fillColor: string
) {
  doc.roundedRect(x, y, w, h, r).fillColor(fillColor).fill();
}

// ---------------------------------------------------------------------------
// Page footer
// ---------------------------------------------------------------------------
function drawPageFooter(
  doc: PDFKit.PDFDocument,
  generatedDate: string,
  pageCounter: { value: number }
) {
  pageCounter.value++;
  const bottom = doc.page.height - 30;
  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const pageWidth = right - left;

  // Save current Y position — footer must not disturb the flow cursor
  const savedY = doc.y;

  doc
    .moveTo(left, bottom - 10)
    .lineTo(right, bottom - 10)
    .strokeColor(C.headerBg)
    .lineWidth(0.5)
    .stroke();

  // Use doc._font.encode + addContent to write text without triggering
  // PDFKit's automatic page-break logic. Alternatively, we temporarily
  // shrink the bottom margin so doc.text() thinks it's within bounds.
  const origBottom = doc.page.margins.bottom;
  doc.page.margins.bottom = 0;

  doc
    .fontSize(7)
    .fillColor(C.muted)
    .text(`Generated by Spendoza on ${generatedDate}`, left, bottom - 6, {
      width: pageWidth,
      align: "center",
      lineBreak: false,
    });

  doc
    .fontSize(7)
    .fillColor(C.muted)
    .text(`Page ${pageCounter.value}`, left, bottom - 6, {
      width: pageWidth,
      align: "right",
      lineBreak: false,
    });

  // Restore margin and Y position
  doc.page.margins.bottom = origBottom;
  doc.y = savedY;
}

// ---------------------------------------------------------------------------
// Drawing: Header banner
// ---------------------------------------------------------------------------
function drawHeaderBanner(
  doc: PDFKit.PDFDocument,
  title: string,
  month: string
) {
  const bannerHeight = 70;
  const pageFullWidth = doc.page.width;

  doc.rect(0, 0, pageFullWidth, bannerHeight).fillColor(C.headerBg).fill();

  doc
    .rect(0, bannerHeight - 4, pageFullWidth, 4)
    .fillColor(C.headerLight)
    .fill();

  doc
    .fontSize(22)
    .fillColor(C.white)
    .text("SPENDOZA", 0, 14, { align: "center", width: pageFullWidth });
  doc
    .fontSize(11)
    .fillColor("#99f6e4")
    .text(title, 0, 38, {
      align: "center",
      width: pageFullWidth,
    });
  doc.fontSize(9).fillColor("#ccfbf1").text(month, 0, 52, {
    align: "center",
    width: pageFullWidth,
  });

  doc.y = bannerHeight + 20;
  doc.x = doc.page.margins.left;
}

// ---------------------------------------------------------------------------
// Drawing: Metric cards (2x2 grid)
// ---------------------------------------------------------------------------
interface MetricCard {
  label: string;
  value: string;
  trend?: string;
  trendPositive?: boolean;
  borderColor: string;
  bgColor: string;
  valueColor: string;
}

function drawMetricCards(doc: PDFKit.PDFDocument, cards: MetricCard[], pageWidth: number) {
  const left = doc.page.margins.left;
  const gap = 10;
  const cardW = (pageWidth - gap) / 2;
  const cardH = 65;
  const startY = doc.y;

  for (let i = 0; i < cards.length; i++) {
    const card = cards[i];
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = left + col * (cardW + gap);
    const y = startY + row * (cardH + gap);

    roundedRect(doc, x, y, cardW, cardH, 4, card.bgColor);
    roundedRect(doc, x, y, 4, cardH, 2, card.borderColor);

    doc
      .fontSize(8)
      .fillColor(C.muted)
      .text(card.label.toUpperCase(), x + 14, y + 10, {
        width: cardW - 20,
      });

    doc
      .fontSize(20)
      .fillColor(card.valueColor)
      .text(card.value, x + 14, y + 22, {
        width: cardW - 20,
      });

    if (card.trend) {
      const arrow = card.trendPositive ? "+" : "-";
      const trendColor = card.trendPositive ? C.income : C.expense;
      doc
        .fontSize(8)
        .fillColor(trendColor)
        .text(`${arrow} ${card.trend} vs last month`, x + 14, y + 47, {
          width: cardW - 20,
        });
    }
  }

  doc.y = startY + 2 * (cardH + gap) + 5;
}

// ---------------------------------------------------------------------------
// Drawing: Section title
// ---------------------------------------------------------------------------
function drawSectionTitle(doc: PDFKit.PDFDocument, title: string, pageWidth: number) {
  ensureSpace(doc, 120);
  const left = doc.page.margins.left;
  doc.fontSize(13).fillColor(C.dark).text(title, left, doc.y);
  const lineY = doc.y + 3;
  doc
    .moveTo(left, lineY)
    .lineTo(left + pageWidth, lineY)
    .strokeColor(C.headerBg)
    .lineWidth(2)
    .stroke();
  doc.y = lineY + 10;
}

// ---------------------------------------------------------------------------
// Drawing: AI Insights callout box
// ---------------------------------------------------------------------------
function drawInsightsBox(doc: PDFKit.PDFDocument, insights: string, pageWidth: number) {
  const left = doc.page.margins.left;
  const padding = 12;
  const innerWidth = pageWidth - padding * 2 - 4;

  // Measure actual text height including word wrap
  const labelHeight = 16;
  doc.fontSize(9);
  const bodyHeight = doc.heightOfString(insights, { width: innerWidth });
  const boxHeight = Math.max(labelHeight + bodyHeight + padding * 2, 50);

  ensureSpace(doc, boxHeight + 10);

  const boxY = doc.y;

  roundedRect(doc, left, boxY, pageWidth, boxHeight, 4, C.netBg);
  roundedRect(doc, left, boxY, 3, boxHeight, 2, C.net);

  doc
    .fontSize(9)
    .fillColor(C.net)
    .text("AI INSIGHTS", left + padding + 4, boxY + padding, {
      width: innerWidth,
    });

  doc
    .fontSize(9)
    .fillColor(C.dark)
    .text(insights, left + padding + 4, boxY + padding + labelHeight, {
      width: innerWidth,
    });

  doc.y = boxY + boxHeight + 12;
}

// ---------------------------------------------------------------------------
// Drawing: Horizontal bar chart
// ---------------------------------------------------------------------------
function drawBarChart(
  doc: PDFKit.PDFDocument,
  categories: Array<{ category: string; amount: number; percentage: number }>,
  totalExpenses: number,
  pageWidth: number
) {
  const left = doc.page.margins.left;
  const barMaxWidth = pageWidth * 0.45;
  const rowHeight = 22;
  const labelWidth = pageWidth * 0.28;
  const barStartX = left + labelWidth;
  const amountX = barStartX + barMaxWidth + 8;
  const maxPct = Math.max(...categories.map((c) => c.percentage), 1);

  for (let i = 0; i < categories.length; i++) {
    const cat = categories[i];
    ensureSpace(doc, rowHeight + 4);

    const y = doc.y;
    const barColor = BAR_COLORS[i % BAR_COLORS.length];

    doc.fontSize(9).fillColor(C.dark).text(cat.category, left, y + 4, {
      width: labelWidth - 8,
    });

    roundedRect(doc, barStartX, y + 3, barMaxWidth, 14, 3, C.divider);

    const barW = Math.max((cat.percentage / maxPct) * barMaxWidth, 2);
    if (barW > 0) {
      roundedRect(doc, barStartX, y + 3, barW, 14, 3, barColor);
    }

    doc
      .fontSize(9)
      .fillColor(C.dark)
      .text(`${fmt(cat.amount)}  ${cat.percentage.toFixed(1)}%`, amountX, y + 4, {
        width: pageWidth - (amountX - left),
      });

    doc.y = y + rowHeight;
  }

  ensureSpace(doc, 30);
  doc
    .moveTo(left, doc.y + 2)
    .lineTo(left + pageWidth, doc.y + 2)
    .strokeColor(C.divider)
    .lineWidth(1)
    .stroke();
  doc.y += 6;
  doc
    .fontSize(10)
    .fillColor(C.dark)
    .text("Total", left, doc.y, { width: labelWidth - 8 });
  doc
    .fontSize(10)
    .fillColor(C.dark)
    .text(fmt(totalExpenses), amountX, doc.y, {
      width: pageWidth - (amountX - left),
    });
  doc.moveDown(1);
}

// ---------------------------------------------------------------------------
// Drawing: Styled table
// ---------------------------------------------------------------------------
function drawStyledTable(
  doc: PDFKit.PDFDocument,
  headers: string[],
  rows: string[][],
  colWidths: number[],
  pageWidth: number,
  options?: { boldCols?: number[]; colColors?: Record<number, string> }
) {
  const left = doc.page.margins.left;
  const headerHeight = 20;
  const rowHeight = 18;

  // Ensure header + at least a few data rows fit on the same page
  const minRows = Math.min(rows.length, 3);
  ensureSpace(doc, headerHeight + 2 + minRows * rowHeight);

  const headerY = doc.y;
  roundedRect(doc, left, headerY, pageWidth, headerHeight, 3, C.headerBg);

  let x = left;
  for (let i = 0; i < headers.length; i++) {
    doc
      .fontSize(8)
      .fillColor(C.white)
      .text(headers[i], x + 6, headerY + 5, {
        width: pageWidth * colWidths[i] - 12,
        lineBreak: false,
      });
    x += pageWidth * colWidths[i];
  }
  doc.y = headerY + headerHeight + 2;

  for (let r = 0; r < rows.length; r++) {
    // Measure actual row height by checking max cell text height
    doc.fontSize(8);
    let maxCellH = rowHeight;
    for (let i = 0; i < rows[r].length; i++) {
      const cellW = pageWidth * colWidths[i] - 12;
      const h = doc.heightOfString(rows[r][i], { width: cellW }) + 8;
      if (h > maxCellH) maxCellH = h;
    }

    if (doc.y > doc.page.height - doc.page.margins.bottom - maxCellH - 10) {
      newPage(doc);
    }

    const rowY = doc.y;
    const isAlt = r % 2 === 1;

    if (isAlt) {
      doc.rect(left, rowY, pageWidth, maxCellH).fillColor(C.rowAlt).fill();
    }

    x = left;
    for (let i = 0; i < rows[r].length; i++) {
      const isBold = options?.boldCols?.includes(i);
      const color = options?.colColors?.[i] ?? C.dark;
      if (isBold) doc.font("Helvetica-Bold");
      doc
        .fontSize(8)
        .fillColor(color)
        .text(rows[r][i], x + 6, rowY + 4, {
          width: pageWidth * colWidths[i] - 12,
        });
      if (isBold) doc.font("Helvetica");
      x += pageWidth * colWidths[i];
    }

    doc
      .moveTo(left, rowY + maxCellH)
      .lineTo(left + pageWidth, rowY + maxCellH)
      .strokeColor(C.divider)
      .lineWidth(0.3)
      .stroke();

    doc.y = rowY + maxCellH;
  }

  doc.moveDown(1);
}

// ---------------------------------------------------------------------------
// Drawing: Callout box
// ---------------------------------------------------------------------------
function drawCalloutBox(
  doc: PDFKit.PDFDocument,
  text: string,
  subtext: string | null,
  pageWidth: number,
  borderColor: string,
  bgColor: string
) {
  const left = doc.page.margins.left;
  const boxHeight = subtext ? 38 : 26;
  ensureSpace(doc, boxHeight + 8);

  const y = doc.y;
  roundedRect(doc, left, y, pageWidth, boxHeight, 4, bgColor);
  roundedRect(doc, left, y, 3, boxHeight, 2, borderColor);

  doc.fontSize(9).fillColor(C.dark).text(text, left + 14, y + 8, {
    width: pageWidth - 28,
  });

  if (subtext) {
    doc.fontSize(8).fillColor(C.muted).text(subtext, left + 14, y + 22, {
      width: pageWidth - 28,
    });
  }

  doc.y = y + boxHeight + 8;
}

// ---------------------------------------------------------------------------
// Drawing: Goal progress
// ---------------------------------------------------------------------------
function drawGoalProgress(
  doc: PDFKit.PDFDocument,
  goals: PdfReportInput["goalProgress"],
  pageWidth: number
) {
  const left = doc.page.margins.left;

  for (const goal of goals) {
    ensureSpace(doc, 55);

    const progressPct =
      goal.target > 0 ? Math.min((goal.current / goal.target) * 100, 100) : 0;
    const onTrack =
      goal.goal_type === "budget"
        ? goal.current <= goal.target
        : goal.current >= goal.target;

    const barColor = goal.goal_type === "budget"
      ? (onTrack ? C.income : C.expense)
      : (onTrack ? C.income : C.amber);

    const statusText = onTrack
      ? "On Track"
      : goal.goal_type === "budget"
        ? "Over Budget"
        : "Behind";
    const statusColor = onTrack ? C.income : (goal.goal_type === "budget" ? C.expense : C.amber);
    const statusBg = onTrack ? C.incomeBg : (goal.goal_type === "budget" ? C.expenseBg : C.amberBg);

    doc.fontSize(10).fillColor(C.dark).text(goal.name, left, doc.y, {
      continued: true,
    });
    doc
      .fontSize(8)
      .fillColor(C.muted)
      .text(
        `  (${goal.goal_type.replace("_", " ")}${goal.category_name ? " — " + goal.category_name : ""})`,
        { continued: false }
      );

    const barY = doc.y + 3;
    const barWidth = pageWidth * 0.65;
    const barHeight = 12;

    roundedRect(doc, left, barY, barWidth, barHeight, 4, C.divider);

    const fillWidth = barWidth * (progressPct / 100);
    if (fillWidth > 0) {
      roundedRect(doc, left, barY, Math.max(fillWidth, 8), barHeight, 4, barColor);
    }

    const displayPct =
      goal.goal_type === "budget"
        ? `${((goal.current / (goal.target || 1)) * 100).toFixed(0)}%`
        : `${progressPct.toFixed(0)}%`;
    doc
      .fontSize(11)
      .fillColor(statusColor)
      .text(displayPct, left + barWidth + 10, barY + 1, {
        width: 40,
      });

    const pillX = left + barWidth + 55;
    const pillW = 65;
    const pillH = 14;
    roundedRect(doc, pillX, barY, pillW, pillH, 7, statusBg);
    doc
      .fontSize(7)
      .fillColor(statusColor)
      .text(statusText, pillX, barY + 3, {
        width: pillW,
        align: "center",
      });

    doc.y = barY + barHeight + 4;

    const currentLabel = goal.goal_type === "budget" ? "Spent" : "Saved";
    let detailText = `${currentLabel}: ${fmt(goal.current)} of ${fmt(goal.target)}`;
    if (goal.target_date) {
      const targetDate = new Date(goal.target_date + "T00:00:00Z");
      detailText += ` — Target: ${targetDate.toLocaleDateString("en-US", {
        month: "short",
        year: "numeric",
        timeZone: "UTC",
      })}`;
    }
    doc.fontSize(8).fillColor(C.muted).text(detailText, left);
    doc.moveDown(0.7);
  }
}

// ---------------------------------------------------------------------------
// Drawing: Savings cards
// ---------------------------------------------------------------------------
function drawSavingsCards(
  doc: PDFKit.PDFDocument,
  recs: PdfReportInput["savingsRecommendations"],
  pageWidth: number
) {
  const left = doc.page.margins.left;

  doc
    .fontSize(8)
    .fillColor(C.muted)
    .text(
      "Based on your spending patterns, here are areas where you may be able to save:",
      left
    );
  doc.moveDown(0.4);

  for (const rec of recs) {
    const boxH = 36;
    ensureSpace(doc, boxH + 6);
    const y = doc.y;

    roundedRect(doc, left, y, pageWidth, boxH, 4, C.amberBg);
    roundedRect(doc, left, y, 3, boxH, 2, C.amber);

    doc
      .fontSize(9)
      .fillColor(C.dark)
      .text(
        `${rec.category}: ${fmt(rec.amount)} (${rec.percentage.toFixed(1)}% of expenses)`,
        left + 14,
        y + 8,
        { width: pageWidth - 28 }
      );
    doc
      .fontSize(8)
      .fillColor(C.muted)
      .text(`- ${rec.suggestion}`, left + 14, y + 22, {
        width: pageWidth - 28,
      });

    doc.y = y + boxH + 6;
  }
}

// ---------------------------------------------------------------------------
// Main builder (same signature as before)
// ---------------------------------------------------------------------------
export function buildReportPdf(input: PdfReportInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const pageCounter = { value: 0 };
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Uint8Array[] = [];
    const generatedDate = new Date().toLocaleDateString("en-US");

    doc.on("data", (chunk: Uint8Array) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth =
      doc.page.width - doc.page.margins.left - doc.page.margins.right;

    activeFooterCtx = { doc, generatedDate, pageCounter };

    // =====================================================================
    // PAGE 1: Header banner + Metric cards + AI Insights
    // =====================================================================
    drawHeaderBanner(doc, input.title, input.month);

    const net = input.reportData.total_income - input.reportData.total_expenses;
    const mom = input.reportData.month_over_month;

    const cards: MetricCard[] = [
      {
        label: "Total Income",
        value: fmt(input.reportData.total_income),
        trend: mom ? `${Math.abs(mom.income_change).toFixed(1)}%` : undefined,
        trendPositive: mom ? mom.income_change >= 0 : undefined,
        borderColor: C.income,
        bgColor: C.incomeBg,
        valueColor: C.income,
      },
      {
        label: "Total Expenses",
        value: fmt(input.reportData.total_expenses),
        trend: mom ? `${Math.abs(mom.expense_change).toFixed(1)}%` : undefined,
        trendPositive: mom ? mom.expense_change <= 0 : undefined,
        borderColor: C.expense,
        bgColor: C.expenseBg,
        valueColor: C.expense,
      },
      {
        label: "Net",
        value: fmt(net),
        borderColor: C.net,
        bgColor: C.netBg,
        valueColor: net >= 0 ? C.net : C.expense,
      },
      {
        label: "Savings Rate",
        value: `${input.reportData.savings_rate.toFixed(1)}%`,
        borderColor: C.savings,
        bgColor: C.savingsBg,
        valueColor: C.savings,
      },
    ];

    drawMetricCards(doc, cards, pageWidth);

    if (input.aiInsights) {
      drawInsightsBox(doc, input.aiInsights, pageWidth);
    }

    // =====================================================================
    // SECTION: Expense Breakdown + Recurring Bills
    // =====================================================================
    if (
      input.reportData.by_category.length > 0 ||
      input.recurringBills.length > 0
    ) {
      // Estimate space for expense breakdown bar chart
      const barChartRows = input.reportData.by_category.length;
      const barChartHeight = barChartRows > 0 ? 30 + barChartRows * 26 + 20 : 0;
      ensureSpace(doc, barChartHeight > 0 ? barChartHeight : sectionStartHeight(input.recurringBills.length));

      if (input.reportData.by_category.length > 0) {
        drawSectionTitle(doc, "Expense Breakdown", pageWidth);
        drawBarChart(
          doc,
          input.reportData.by_category,
          input.reportData.total_expenses,
          pageWidth
        );
      }

      if (input.recurringBills.length > 0) {
        drawSectionTitle(doc, "Recurring Bills", pageWidth);
        const headers = ["Bill", "Amount", "Frequency", "Next Due"];
        const rows = input.recurringBills.map((b) => [
          b.friendly_name || b.description,
          fmt(b.amount),
          b.recurrence_interval ?? "—",
          b.next_due_date
            ? new Date(b.next_due_date + "T00:00:00Z").toLocaleDateString(
                "en-US",
                { timeZone: "UTC" }
              )
            : "—",
        ]);
        drawStyledTable(doc, headers, rows, [0.35, 0.2, 0.2, 0.25], pageWidth, {
          boldCols: [1],
        });
      }
    }

    // =====================================================================
    // SECTION: Income Sources + Subscriptions + Goals
    // =====================================================================
    if (
      input.incomeSources.length > 0 ||
      input.subscriptionsPaid.length > 0 ||
      input.goalProgress.length > 0
    ) {
      const nextSectionRows = input.incomeSources.length || input.subscriptionsPaid.length || input.goalProgress.length;
      ensureSpace(doc, sectionStartHeight(nextSectionRows));

      if (input.incomeSources.length > 0) {
        drawSectionTitle(doc, "Income Sources", pageWidth);
        const headers = ["Source", "Amount", "Frequency", "Attributed To"];
        const rows = input.incomeSources.map((i) => [
          i.source_name,
          fmt(i.amount),
          i.frequency,
          i.attributed_to_name ?? "Self",
        ]);
        drawStyledTable(
          doc,
          headers,
          rows,
          [0.3, 0.2, 0.2, 0.3],
          pageWidth
        );
      }

      if (input.subscriptionsPaid.length > 0) {
        drawSectionTitle(doc, "Subscriptions", pageWidth);
        const subHeaders = ["Name", "Amount", "Frequency", "Category"];
        const subRows = input.subscriptionsPaid.map((s) => [
          s.name,
          fmt(s.amount),
          s.recurrence_interval,
          s.category ?? "—",
        ]);
        drawStyledTable(
          doc,
          subHeaders,
          subRows,
          [0.35, 0.2, 0.2, 0.25],
          pageWidth
        );

        const totalSubs = input.subscriptionsPaid.reduce(
          (sum, s) => sum + s.amount,
          0
        );
        const subPct =
          input.reportData.total_expenses > 0
            ? ((totalSubs / input.reportData.total_expenses) * 100).toFixed(1)
            : "0.0";
        drawCalloutBox(
          doc,
          `Total Subscription Cost: ${fmt(totalSubs)}/mo`,
          `Subscriptions represent ${subPct}% of total expenses`,
          pageWidth,
          C.amber,
          C.amberBg
        );
      }

      if (input.goalProgress.length > 0) {
        drawSectionTitle(doc, "Goal Progress", pageWidth);
        drawGoalProgress(doc, input.goalProgress, pageWidth);
      }
    }

    // =====================================================================
    // SECTION: Savings Opportunities + Member Contributions
    // =====================================================================
    const hasSavings = input.savingsRecommendations.length > 0;
    const hasMembers =
      input.memberContributions && input.memberContributions.length > 0;

    if (hasSavings || hasMembers) {
      const savingsCardH = hasSavings ? 30 + Math.min(input.savingsRecommendations.length, 2) * 70 : 0;
      const memberRows = hasMembers && input.memberContributions ? input.memberContributions.length : 0;
      ensureSpace(doc, savingsCardH > 0 ? savingsCardH : sectionStartHeight(memberRows));

      if (hasSavings) {
        drawSectionTitle(doc, "Savings Opportunities", pageWidth);
        drawSavingsCards(doc, input.savingsRecommendations, pageWidth);
      }

      if (hasMembers && input.memberContributions) {
        drawSectionTitle(doc, "Member Contributions", pageWidth);
        const headers = ["Member", "Income", "Expenses"];
        const rows = input.memberContributions.map((m) => [
          m.display_name,
          fmt(m.income),
          fmt(m.expenses),
        ]);
        drawStyledTable(doc, headers, rows, [0.4, 0.3, 0.3], pageWidth, {
          colColors: { 1: C.income, 2: C.expense },
        });
      }
    }

    // Final page footer
    drawPageFooter(doc, generatedDate, pageCounter);
    activeFooterCtx = null;

    doc.end();
  });
}
